### PR TITLE
Update readmissions model for bug

### PR DESCRIPTION
**Pull request by laurier-empassion**
## Describe your changes
This adds logic to include index admissions when the following encounters are transfers. Currently in the TUVA model (will post to their slack), if an index admission has 1 or more encounters after it with admit/discharge dates the same as the encounter before it, then there is a flag that is created that indicates these are overlapping encounters and all 3 encounters are removed. 

However, we want to keep the first admit date and last encounters' discharge date for further readmission counting. Also commenting out the paid_amount because it will be incorrect as we are combining data from multiple rows.

Also removing lengths of stay over 120 days, those are likely errors in 1 of 2 scenarios I accounted for, this removes around 120 encounters total.

This change adds 2,175 encounters, about a 10% increase and 660+ readmissions overall. 

**Looker Dashboards that be impacted:** 

- Account management dashboard, counts of readmissions 

Another review that this example shows this was a transfer

```
select *
from production-dna.analytics_int.encounter
--production-dna.analytics_int.stg_encounter
--production-dna.analytics_int.encounter_data_quality
where encounter_id in ('1002032226392', '1002032226413', '1002057086018')


```

```
select count(distinct encounter_id)
 from `pre-production-dna.dbt_lrosenbluth_int.readmission_summary` 
 where readmit_30_flag=1
--19023
--readmit number 3679
 ;

 select count(distinct encounter_id)

 from `production-dna.analytics_int.readmission_summary` 
  where readmit_30_flag=1

```

Example encounter id's '1002032226392', '1002032226413', '1002057086018' , can look in production-dna.analytics_int.encounter_data_quality

## How has this been tested?
Unique and not null tests on the yml
Counts and tests in BQ along with visual inspection of records. 

## Reviewer focus
Please summarize the specific items you’d like the reviewer(s) to look into.

## Checklist before requesting a review
- [x]  My code follows style guidelines
- [x]  I have tested my code by running `dbt build` in **BigQuery**
- [x]  (New models only) I have implemented generic dbt tests to validate primary keys/uniqueness in my model
- [ ]  I have added at least one Github label to this PR

## (Optional) Gif of how this PR makes you feel

https://tenor.com/view/rod-serling-youve-entered-the-burnout-zone-gif-16697452

### CODE REVIEW

**Review by emp-maazmushtaq — COMMENTED** [review]
I think I follow what's happening and I'm onboard with the proposed logic changes. Before approving, can we get an understanding of the impact that this change has on any dashboards or Explores in Looker?

**Comment by mattvivier** [comment]
It sounds like you and @chase-jones have spent a lot of time on the logic here, so I'll defer to you all. I would just ask that we ping the team channel to remind everyone to do a `dbt deps` if that's needed to pull these changes locally for their future runs.

**Review by chase-jones — APPROVED** [review]
Looks good to me, verified this would be additions to this encounters table only. Ran through a couple of ad-hoc examples.

In addition, Maaz's concern of downstream impacts, I don't see any personally after running `dbt ls --select readmissions__readmission_summary+ --resource-type model`.

Telling team to run `dbt clean` then `dbt deps` not urgent as no downstream models. 

Nitpick would be to run linter, but not blocking. Approving.

**Comment by laurier-empassion** [comment]
> Looks good to me, verified this would be additions to this encounters table only. Ran through a couple of ad-hoc examples.
> 
> In addition, Maaz's concern of downstream impacts, I don't see any personally after running `dbt ls --select readmissions__readmission_summary+ --resource-type model`.
> 
> Telling team to run `dbt clean` then `dbt deps` not urgent as no downstream models.
> 
> Nitpick would be to run linter, but not blocking. Approving.

Yay! I ran linter, but for some reason there were only 'non fixable issues'.

**Pull request merged**
